# Generated by Django 2.1.4 on 2019-01-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyFortress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dev_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='设备组')),
                ('describe', models.CharField(max_length=512, verbose_name='设备组描述')),
            ],
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='主机名')),
                ('ipaddr', models.CharField(max_length=64, verbose_name='ip地址')),
                ('status', models.SmallIntegerField(choices=[(0, '启用'), (1, '禁用')])),
                ('remarks', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
                ('group', models.ManyToManyField(to='MyFortress.dev_group')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='设备角色')),
                ('describe', models.CharField(max_length=512, verbose_name='角色描述')),
            ],
        ),
        migrations.AddField(
            model_name='hostlist',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFortress.Roles'),
        ),
    ]
