# Generated by Django 2.1.4 on 2019-01-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyFortress', '0002_auto_20190104_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='abc', max_length=64, verbose_name='运营商')),
            ],
        ),
        migrations.AddField(
            model_name='hostlist',
            name='isp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyFortress.ISP'),
        ),
    ]
