# Generated by Django 2.1.4 on 2019-01-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyFortress', '0003_auto_20190104_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFortress.ISP'),
        ),
        migrations.AlterField(
            model_name='isp',
            name='name',
            field=models.CharField(max_length=64, verbose_name='运营商'),
        ),
    ]
